{% set name = "decoupler" %}
{% set conda_package_name = "decoupler-py" %}
{% set version = "1.9.2" %}

package:
  name: {{ conda_package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/decoupler-{{ version }}.tar.gz
  sha256: 9b3f75673311635fd30228273f953cc2b3d3886bcebff83abadfc9200951a7f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . liana>=1.5.0 -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - scikit-learn
    - igraph
    - adjusttext >=1.1.1
    - pydeseq2 <0.5.0
    - marsilea >=0.4.5
    - pybiomart
    - scanpy

test:
  imports:
    - decoupler
  commands:
    - pip check
  requires:
    - pip
    - poetry
    - python {{ python_min }}

about:
  home: https://github.com/saezlab/decoupler-py
  summary: Ensemble of methods to perform enrichment analysis from omics data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PauBadiaM
