{% set name = "decoupler" %}
{% set conda_package_name = "decoupler-py" %}
{% set version = "2.1.3" %}

package:
  name: {{ conda_package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/decoupler-{{ version }}.tar.gz
  sha256: 3f8d1380d1478757e353ac0ed9851902503d50fd80e79c4bf3f7b095c9132a4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - scanpy
    - docrep
    - xgboost
    - requests
    - marsilea
    - adjusttext
    - python-igraph
    - ipywidgets
    - dcor

test:
  imports:
    - decoupler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/decoupler
  summary: Ensemble of methods to perform enrichment analysis from omics data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PauBadiaM
