{% set name = "decoupler" %}
{% set conda_package_name = "decoupler-py" %}
{% set version = "1.8.0" %}

package:
  name: {{ conda_package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/decoupler-{{ version }}.tar.gz
  sha256: 4f6cda3fb2c807ff8681f1d15c3167e14f3a419378b4446c8ede3b60d40afb74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - numba
    - tqdm
    - anndata
    - typing-extensions
    - scikit-learn
    - omnipath
    - adjustText
    - scanpy
    - seaborn
    - pandas
    - scipy
    - numpy <2.0.0
    - typing_extensions
    - python-igraph >=0.10.0

test:
  imports:
    - decoupler
  commands:
    - pip check
  requires:
    - pip
    - poetry
    - python {{ python_min }}

about:
  home: https://github.com/saezlab/decoupler-py
  summary: Ensemble of methods to perform enrichment analysis from omics data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PauBadiaM
