{% set name = "decoupler" %}
{% set conda_package_name = "decoupler-py" %}
{% set version = "2.1.4" %}

package:
  name: {{ conda_package_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/decoupler-{{ version }}.tar.gz
  sha256: 356a6010676c8aa199e9e8286e405544d22f1dd8a14a840779c8734423720048

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - scanpy
    - docrep
    - xgboost
    - requests
    - marsilea
    - adjusttext
    - python-igraph
    - ipywidgets
    - dcor

test:
  imports:
    - decoupler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/decoupler
  summary: Ensemble of methods to perform enrichment analysis from omics data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PauBadiaM
